### ISSUE TITLE
Megaman Wily Wars SRAM hack not saving

### ISSUE THREAD

**Issue by Brianvgplayer** [MiSTer-devel/MegaDrive_MiSTer#27]
Hi. I have been using [this hack](https://www.romhacking.net/hacks/7257/). It saves on the old core and the Mega Everdrive Pro, but not on the newer Megadrive core. Autosave is on, but the "saving..." message never comes up and no file is saved. Saving message comes up on the old Genesis core and on the non-hacked Wily Wars roms that use eeprom.

**Comment by MP2E** [comment]
Not a core bug, the core sees that the cartridge ID in the header is for Wily Wars and enables eeprom saving. The reason it works on the old Genesis core is because that didn’t support eeprom saving in the first place.

To fix saving on this hack, you can open the patched rom in a hex editor and look for “T-12046 “ near the very beginning of the file. Simply change that ID to something else, like say “T-12046A” and it will then work with the mister core.

**Comment by sorgelig** [comment]
That's the problem of hacks. They leave old ID making it impossible to distinguish.
